workflows:
  android-workflow:
    name: Android Workflow

    environment:
      flutter: stable

    scripts:
      - name: Disable iOS
        script: |
          rm -rf ios
          flutter clean
          flutter pub get

      - name: Build Android
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/**/*.aab