workflows:
  android-workflow:
    name: Android Workflow

    environment:
      flutter: stable

    scripts:
      - name: Prepare build
        script: |
          flutter clean

          rm -rf build
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock

          mkdir -p build/ios/SourcePackages

          flutter pub get

      - name: Build Android
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/**/*.aab