// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALl26nTgGzcK0-Up8A5fMf22EeJR_K5hY',
    appId: '1:611853205338:web:0ed1051f12907e2577fd63',
    messagingSenderId: '611853205338',
    projectId: 'fm002kanri',
    authDomain: 'fm002kanri.firebaseapp.com',
    storageBucket: 'fm002kanri.firebasestorage.app',
    measurementId: 'G-XQNKF2VD6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUuqRhqDq1ecAheUWJLUkeEMeZAQADrsU',
    appId: '1:611853205338:android:8de5a6bd512a35dd77fd63',
    messagingSenderId: '611853205338',
    projectId: 'fm002kanri',
    storageBucket: 'fm002kanri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHk4qvYgkYtyg6eQfZqOrwefrcd-Mz67I',
    appId: '1:611853205338:ios:c2a185765d99562277fd63',
    messagingSenderId: '611853205338',
    projectId: 'fm002kanri',
    storageBucket: 'fm002kanri.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHk4qvYgkYtyg6eQfZqOrwefrcd-Mz67I',
    appId: '1:611853205338:ios:c2a185765d99562277fd63',
    messagingSenderId: '611853205338',
    projectId: 'fm002kanri',
    storageBucket: 'fm002kanri.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALl26nTgGzcK0-Up8A5fMf22EeJR_K5hY',
    appId: '1:611853205338:web:c763e9972e7bf8c777fd63',
    messagingSenderId: '611853205338',
    projectId: 'fm002kanri',
    authDomain: 'fm002kanri.firebaseapp.com',
    storageBucket: 'fm002kanri.firebasestorage.app',
    measurementId: 'G-64R62W2B0K',
  );
}
